jira:
  server: " " #add Jira Server Name here
  username: " " #add your Jira Username 
  token: " " #Jira access token 

# OpenAI Configuration
openai:
  api_key: " "
  model: " "

# JQL Query for Different Scripts
queries:
  ticket_scores:
    jql: "project = XYZ AND issuetype = Task AND Sprint = 123"
  backlog:
    jql: 'project = XYZ AND Sprint IS EMPTY AND statusCategory != Done'


# Prompts for Different Checks
prompts:
  relevance: |
    You are a helpful assistant. A Jira ticket has the following summary: "{summary}".
    The description provided is: "{description}". For now, take only 5 tickets from the backlog section.
    Rate how well the description aligns with the summary on a scale of 1 to 10, where 1 means not aligned at all and 10 means perfectly aligned. Also, provide a brief explanation (not more than one line) for the score and write it as Relevance Score:.

  adherence: |
    You are a helpful assistant. A Jira ticket has the following description under the Description heading: "{description}".
    The template requires the following sections: {", ".join(headings)}.
    Check how many of these sections are present and rate the adherence as a percentage. Write it as Adherence Percentage:

  other_check: |
    You are a helpful assistant. Analyze the following Jira ticket: "{summary}". Provide a brief summary and rate the quality on a scale of 1 to 10, where 1 is poor and 10 is excellent.

# Output Configuration for Different Scripts
output_files:
  ticket_scores: "jira_ticket_scores.csv"
  backlog: "backlog.csv"

# Template Headings
template_headings:
  - "Summary"
  - "Steps to Reproduce"
  - "Technical Notes"
  - "Testing Instructions"

# Score Calculation Formula
scoring:
  weightage_of_relevance: 0.5
  weightage_of_adherence: 0.5
