jira:
  server: " " #add Jira Server Name here
  username: " " #add your Jira Username 
  token: " " #Jira access token 

# OpenAI Configuration
openai:
  api_key: " "
  model: " "

# Parameters
parameters:
  project: " "
  issuetype: " "
  sprint: " "

# JQL Queries
queries:
  ticket_scores: "project = {project} AND issuetype = {issuetype} AND Sprint = {sprint}"
  backlog: "project = {project} AND Sprint IS EMPTY AND statusCategory != Done"

template_headings:
  task_template_headings:
    - "Summary"
    - "Acceptability Criteria"
    - "Technical Notes"
    - "Testing Instructions"

  bug_template_headings:
    - "Summary"
    - "Steps to Reproduce"
    - "Technical Notes"
    - "Testing Instructions"

# Prompts for Different Checks
prompts:
  relevance: |
    You are a helpful assistant. A Jira ticket has the following summary: "{summary}".
    The description provided is: "{description}". Please analyze it based on the provided template headings.
    Rate how well the description aligns with the summary on a scale of 1 to 10, where 1 means not aligned at all and 10 means perfectly aligned. Also, provide a brief explanation for the score as Relevance Score.
    Write Relevance Score as Relevance Score: 

  adherence: |
    You are a helpful assistant. A Jira ticket has the following description under the Description heading: "{description}".
    The template requires the following sections: {headings}.
    Check how many of these sections are present and rate the adherence as a percentage.  Write it as Adherence Score:

# Output Configuration for Different Scripts
output_files:
  ticket_scores: "jira_ticket_scores.csv"
  backlog: "backlog.csv"

# Score Calculation Formula
scoring:
  weightage_of_relevance: 0.5
  weightage_of_adherence: 0.5

# Template Placeholders
template_placeholders:
  bug:
    summary: "[A concise description of the issue or task.]"
    steps_to_reproduce: "[Detailed steps that lead to the issue, including screenshots if possible.]"
    technical_notes: "[Any technical information that might be helpful for the developer, such as dependencies, libraries, or code snippets.]"
    testing_instructions: "[Instructions or considerations for testing the task or fix.]"

  task:
    summary: "[A concise description of the task.]"
    steps_to_reproduce: "[Detailed steps to complete the task.]"
    technical_notes: "[Technical information relevant to the task.]"
    testing_instructions: "[Instructions for verifying the task's completion.]"




