import os
import subprocess
import boto3
from botocore.exceptions import NoCredentialsError
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders


# Paths to your scripts
script1_path = "/app/ticket_scores.py"
script2_path = "/app/backlog.py"


# Run the first script
subprocess.run(["python", script1_path])

# Run the second script
subprocess.run(["python", script2_path])

# AWS SES Configuration
SES_REGION = os.getenv('SES_REGION')
SES_SENDER = os.getenv('SES_SENDER')
SES_RECIPIENT = os.getenv('SES_RECIPIENT')
AWS_ACCESS_KEY = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')

def send_email():
    ses_client = boto3.client('ses', region_name=SES_REGION,
                              aws_access_key_id=AWS_ACCESS_KEY,
                              aws_secret_access_key=AWS_SECRET_KEY)

    subject = "Weekly Jira Script Reports"
    body_text = ("Here are the weekly reports generated by the Jira scripts.\n"
                 "Please find the attached files.")
    
    # Attachments
    files = ["sprint_report.xlsx", "backlog_report.xlsx"]

    msg = MIMEMultipart()
    msg['Subject'] = subject
    msg['From'] = SES_SENDER
    msg['To'] = SES_RECIPIENT
    
    # Message body
    msg.attach(MIMEText(body_text, 'plain'))
    
    # Attach each file
    for file in files:
        attachment = MIMEBase('application', "octet-stream")
        attachment.set_payload(open(file, "rb").read())
        encoders.encode_base64(attachment)
        attachment.add_header('Content-Disposition', f'attachment; filename= {os.path.basename(file)}')
        msg.attach(attachment)

    # Send email
    try:
        response = ses_client.send_raw_email(
            Source=SES_SENDER,
            Destinations=[SES_RECIPIENT],
            RawMessage={
                'Data': msg.as_string(),
            }
        )
        print("Email sent! Message ID:", response['MessageId'])
    except NoCredentialsError:
        print("Credentials not available")
    except Exception as e:
        print(f"Failed to send email: {e}")

# Call the function to send the email
send_email()