# jira_functions.py

JIRA_CONNECTION_FAILURE = "JIRA connection established successfully."
JIRA_CONNECTION_SUCCESS = "Failed to connect to JIRA: "
EPIC = "Epic"
NO_PARENT_EPIC = "No Parent"
ISSUE_PRIOROTY_NOT_ASSIGNED = "No Priority Found"

# ticket_health.py

SYSTEM_MESSAGE = "You are a helpful assistant."
RELEVANCE_SCORE_NOT_FOUND = "Relevance Score Not Found"
ADHERENCE_SCORE_NOT_FOUND = "Adherence Score Not Found"
DATAFRAME_EMPTY = "DataFrame is empty. No data to plot."

# email.py

EMAIL_SUBJECT = "Weekly Jira Script Reports"
EMAIL_BODY_TEXT = "Here are the weekly reports generated by the Jira scripts.\nPlease find the attached files."
NO_CREDENTIALS_ERROR = "AWS credentials not available"
EMAIL_SENDING_FAILED = "Failed to send email"
FILE_NOT_FOUND = "File not found. Skipping attachment."

# ticket_scores.py

NO_AMMENDMENTS_REQUIRED = "No Ammendments Required"